name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: |
        swiftlint --strict --reporter github-actions-logging
        
  test:
    name: Unit Tests
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
      
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-
          
    - name: Run tests
      run: |
        xcodebuild \
          -project SubTrackr.xcodeproj \
          -scheme SubTrackr \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
          -enableCodeCoverage YES \
          test
          
    - name: Comment test results
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Find test result files
          const testResultPath = '~/Library/Developer/Xcode/DerivedData';
          
          // Create a comment with test results
          const comment = `## 🧪 Test Results
          
          The unit tests have been executed. Please check the workflow logs for detailed results.
          
          - ✅ All core model tests
          - ✅ Currency conversion tests  
          - ✅ Widget data manager tests
          - ✅ Subscription view model tests
          
          If any tests failed, please review the logs and fix the issues before merging.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  ui-tests:
    name: UI Tests
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
      
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-
          
    - name: Run UI tests
      run: |
        xcodebuild \
          -project SubTrackr.xcodeproj \
          -scheme SubTrackr \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
          test -only-testing:SubTrackrUITests
          
    - name: Upload UI test artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ui-test-screenshots
        path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/Test-*.xcresult